baseURL = "https://guzhongren.github.io"
# [en, zh, ...] determines default content language
# [en, zh, ...] 设置默认的语言
defaultContentLanguage = "zh"
# theme
# 主题
theme = "LoveIt"
# themes directory
# 主题目录
themesDir = "./themes"

# whether to use robots.txt
# 是否使用 robots.txt
enableRobotsTXT = true
# whether to use git commit log to generate lastmod record
# 是否使用 git 信息来生成文章的上次修改时间
enableGitInfo = true
# whether to use emoji code
# 是否使用 emoji 代码
enableEmoji = true

[languages]
  [languages.zh]
    weight = 2
    # 网站语言
    languageCode = "zh"
    # 网站标题
    title = "谷中仁的博客"
    # 是否包括中日韩文字
    hasCJKLanguage = true
    # 默认每页列表显示的文章数目
    paginate = 100
    # [UA-XXXXXXXX-X] 谷歌分析代号
    googleAnalytics = "UA-158950474-1"
    # 版权描述，仅仅用于 SEO
    copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License."
    # 日期格式
    dateFormatToUse = "2006-01-02"
    # 菜单信息
    [languages.zh.menu]
      [[languages.zh.menu.main]]
        identifier = "posts"
        name = "文章"
        url = "/posts/"
        weight = 1
      [[languages.zh.menu.main]]
        identifier = "tags"
        name = "标签"
        url = "/tags/"
        weight = 2
      [[languages.zh.menu.main]]
        identifier = "categories"
        name = "分类"
        url = "/categories/"
        weight = 3
      [[languages.zh.menu.main]]
        identifier = "about"
        name = "关于"
        url = "/about/"
        weight = 4
    [languages.zh.params]
      # LoveIt 主题版本
      version = "0.1.X"
      # 网站描述
      description = "关于 LoveIt 主题"
      # 网站关键词
      keywords = ["guzhongren", "dev", "consultant", "full stack", "freeCoodeCamp", "fcc", "ThoughtWorks"]
      # 网站默认主题 ("light", "dark", "auto")
      defaultTheme = "auto"
      # 用于生成文章上次修改时间的公共 git 仓库路径，仅在 enableGitInfo 设为 true 时有效
      gitRepo = ""
      # 页面头部导航栏信息
      [languages.zh.params.header]
        # 桌面端导航栏模式 ("fixed", "normal", "auto")
        desktopMode = "fixed"
        # 移动端导航栏模式 ("fixed", "normal", "auto")
        mobileMode = "auto"
      # 页面底部版权信息设置
      [languages.zh.params.footer]
        # 网站创立年份
        since = 2019
        # ICP 备案信息，仅在中国使用 (允许使用 HTML 格式)
        icp = ""
        # 许可协议信息 (允许使用 HTML 格式)
        license= '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'
      # 主页信息设置
      [languages.zh.params.home]
        # 主页个人信息
        [languages.zh.params.home.profile]
          enable = true
          # Gravatar 邮箱，用于优先在主页显示的头像
          gravatarEmail = ""
          # 主页显示头像的 URL
          avatarURL = "images/avatar.png"
          # 主页显示的网站副标题
          subtitle = "一位极客、全栈开发者、freeCodeCamp 西安社区组织者、ThoughtWorks 咨询师..."
          # 是否为副标题显示打字机动画
          typeit = true
          # 是否显示社交账号
          social = true
        # 主页文章列表
        [languages.zh.params.home.posts]
          enable = true
          # 主页每页显示文章数量
          paginate = 10
          # 当你没有在文章前面设置 "hiddenFromHomePage" 时的默认行为
          defaultHiddenFromHomePage = false
      # 主页的社交信息设置
      [languages.zh.params.social]
        GitHub = "guzhongren"
        FreeCodeCamp = "guzhongren"
        Email = "guzhongren@live.cn"
        Zhihu = "guzhongren"
        # Linkedin = "xxxx"
        # Twitter = "xxxx"
        # Instagram = "xxxx"
        # Facebook = "xxxx"
        # Telegram = "xxxx"
        # Medium = "xxxx"
        # Gitlab = "xxxx"
        # Youtubelegacy = "xxxx"
        # Youtubecustom = "xxxx"
        # Youtubechannel = "xxxx"
        # Tumblr ="xxxx"
        # Quora = "xxxx"
        # Keybase = "xxxx"
        # Pinterest = "xxxx"
        # Reddit = "xxxx"
        # Codepen = "xxxx"
        # Bitbucket = "xxxx"
        # Stackoverflow = "xxxx"
        # Weibo = "xxxx"
        # Odnoklassniki = "xxxx"
        # VK = "xxxx"
        # Flickr = "xxxx"
        # Xing = "xxxx"
        # Snapchat = "xxxx"
        # Soundcloud = "xxxx"
        # Spotify = "xxxx"
        # Bandcamp = "xxxx"
        # Paypal = "xxxx"
        # Fivehundredpx = "xxxx"
        # Mix = "xxxx"
        # Goodreads = "xxxx"
        # Lastfm = "xxxx"
        # Foursquare = "xxxx"
        # Hackernews = "xxxx"
        # Kickstarter = "xxxx"
        # Patreon = "xxxx"
        # Steam = "xxxx"
        # Twitch = "xxxx"
        # Strava = "xxxx"
        # Skype = "xxxx"
        # Whatsapp = "xxxx"
        # Douban = "xxxx"
        # Angellist = "xxxx"
        # Slidershare = "xxxx"
        # Jsfiddle = "xxxx"
        # Deviantart = "xxxx"
        # Behance = "xxxx"
        # Dribble = "xxxx"
        # Wordpress = "xxxx"
        # Vine = "xxxx"
        # Googlescholar = "xxxx"
        # Researchgate = "xxxx"
        # Mastodon = "@xxxx"
        # MastodonPrefix = "https://mastodon.technology/"
        # Thingiverse = "xxxx"
        # Devto = "xxxx"
        # Gitea = "xxxx"
        # XMPP = "xxxx@example.com"
        # Matrix = "xxxx"
        # Bilibili = "xxxx"
      # 文章页面配置
      [languages.zh.params.page]
        # 在文章页面是否使用分享功能
        socialShare = true
        # 是否在文章页面显示原始 Markdown 文档链接
        linkToMarkdown = true
      # 文章页面的分享信息设置
      [languages.zh.params.share]
        enable = true
        Twitter = true
        Facebook = true
        # Linkedin = true
        # Whatsapp = true
        # Pinterest = true
        # Tumblr = true
        # HackerNews = true
        # Reddit = true
        # VK = true
        # Buffer = true
        # Xing = true
        # Line = true
        # Instapaper = true
        # Pocket = true
        # Digg = true
        # Stumbleupon = true
        # Flipboard = true
        Weibo = true
        Renren = true
        # Myspace = true
        # Blogger = true
        Baidu = true
        # Odnoklassniki = true
        Evernote = true
        # Skype = true
        # Trello = true
        # Mix = true
      # 数学公式 (KaTeX https://katex.org/)
      [languages.zh.params.math]
        enable = true
        # 默认内联定界符是 $ ... $ 和 \\( ... \\)
        inlineLeftDelimiter = ""
        inlineRightDelimiter = ""
        # 默认块定界符是 $$ ... $$ 和 \\[ ... \\]
        blockLeftDelimiter = ""
        blockRightDelimiter = ""
        # KaTeX 插件 copy_tex
        copyTex = true
        # KaTeX 插件 mhchem
        mhchem = true
      # CSS 和 JS 文件的 CDN 设置
      [languages.zh.params.cdn]
        ## 例如 '<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.10.1/css/all.min.css" integrity="sha256-fdcFNFiBMrNfWL6OcAGQz6jDgNTRxnrLEd4vJYFWScE=" crossorigin="anonymous">'
        fontawesomeFreeCSS = ''
        animateCSS = ''
        gitalkCSS = ''
        gitalkJS = ''
        valineJS = ''
        lazysizesJS = ''
        smoothScrollJS = ''
        sharerJS = ''
        katexCSS = ''
        katexJS = ''
        katexAutoRenderJS = ''
        katexCopyTexCSS = ''
        katexCopyTexJS = ''
        katexMhchemJS = ''
        mermaidJS = ''
        echartsJS = ''
        echartsMacaronsJS = ''
        typeitJS = ''
        aplayerCSS = ''
        aplayerJS = ''
        metingJS = ''
      # 网站验证代码，用于 Google/Bing/Yandex/Pinterest/Baidu
      [languages.zh.params.verification]
        google = ""
        bing = "https://cn.bing.com/?mkt=zh-CN"
        yandex = ""
        pinterest = ""
        baidu = ""
      # 出版者信息，仅用于 SEO
      [languages.zh.params.publisher]
        name = "谷中仁"
        [languages.zh.params.publisher.logo]
          url = "images/avatar.png"
          width = 127
          height = 40
      # 网站图标信息，仅用于 SEO
      [languages.zh.params.logo]
        url = "images/avatar.png"
        width = 127
        height = 40
      #  网站图标信息，仅用于 SEO
      [languages.zh.params.image]
        url = "images/avatar.png"
        width = 800
        height = 600
      # 评论系统设置
      [languages.zh.params.comment]
        enable = true
        # Disqus 评论系统设置 (https://disqus.com/)
        [languages.zh.params.comment.disqus]
          # Disqus 的用户名，用来在文章中启用 Disqus 评论系统
          shortname = "dillonzq"
        # Gittalk 评论系统设置 (https://github.com/gitalk/gitalk)
        [languages.zh.params.comment.gitalk]
          owner = ""
          repo = ""
          clientId = "2e18563cb40ddba68205"
          clientSecret = "3e8682bc8126337a224209fb72e87d09f27a9701"
        # Valine 评论系统设置 (https://github.com/xCss/Valine)
        [languages.zh.params.comment.valine]
          enable = false
          appId = ""
          appKey = ""
          placeholder = "你的评论 ..."
          notify = false
          verify = true
          avatar = "mp"
          # meta= ""
          pageSize = 10
          visitor = true
          recordIP = true
        # Facebook 评论系统设置 (https://developers.facebook.com/docs/plugins/comments)
        [languages.zh.params.comment.facebook]
          enable = false
          width = "100%"
          numPosts = 10
          appId = ""
          languageCode = "en_US"

# Markup related configuration in Hugo
# Hugo 解析文档的配置
[markup]
  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
  # 代码高亮设置 (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = false
    style = "monokai"
    tabWidth = 4
  # Goldmark is from Hugo 0.60 the default library used for Markdown
  # Goldmark 是 Hugo 0.60 以来的默认 Markdown 解析库
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.renderer]
      # whether to use HTML tags directly in the document
      # 是否在文档中直接使用 HTML 标签
      unsafe = true
  # Table Of Contents settings
  # 目录设置
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 6

# Author Info
# 作者信息
[author]
  name = "谷中仁"
  link = "https://guzhongren.github.io"

# Sitemap Info
# 网站地图信息
[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

# Permalinks Info (https://gohugo.io/content-management/urls/#permalinks)
# Permalinks 信息 (https://gohugo.io/content-management/urls/#permalinks)
[Permalinks]
  posts = ":year/:month/:filename"
  # posts = ":filename"

# Privacy Info (https://gohugo.io/about/hugo-and-gdpr/)
# 隐私信息设置 (https://gohugo.io/about/hugo-and-gdpr/)
[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true

  [privacy.youtube]
    privacyEnhanced = true

# Options to make output .md files
# 用于输出 Markdown 格式文档的设置
[mediaTypes]
  [mediaTypes."text/plain"]
    suffixes = ["md"]

# Options to make output .md files
# 用于输出 Markdown 格式文档的设置
[outputFormats.MarkDown]
  mediaType = "text/plain"
  isPlainText = true
  isHTML = false

# Options to make hugo output files
# 用于 Hugo 输出文档的设置
[outputs]
  home = ["HTML", "RSS"]
  page = ["HTML", "MarkDown"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
  taxonomyTerm = ["HTML"]
